name: branch-cleanup
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: hello
        id: hello
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: 'Mona the Octocat'
