name: branch-cleanup
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

uses: actions/hello-world-docker-action@master
with:
  who-to-greet: 'Mona the Octocat'
