name: hello
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  helloworld:
    env:
      foo: 'foobar'
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world $foo, $GITHUB_REF, $GITHUB_SHA
        #        env:
        #          GITHUB_REF: The
        #          Last_Name: Octocat
  hello:
    needs: helloworld
    env:
      foo: 'foobar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: hello
        id: hello
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: {{ job.env.foo }}


